### ISSUE TITLE
Can't include more than one code block from the same file

### ISSUE THREAD

**Issue by unleashit** [jknoxville/remark-code-snippets#1]
Thanks for the plugin. It's very useful. Not sure if you're still maintaining it, but when I try to import two or more sections of code from the same file I get an error. This is from two different code blocks (and different marker names). For example:

\```typescript file=./packages/login/src/types.ts start=start_mdx_hook end=end_mdx_hook
\```

\```typescript file=./packages/login/src/types.ts start=start_mdx_hook2 end=end_mdx_hook2
\```
results in the error:

Error: MDX compilation failed for file "/home/jg/www/npm-library/shared/docs/docs/components/login.mdx"
Cause: Ambiguous code block start marker. Found more than once in ./shared/common/src/types.ts, at lines 27,50
Details:
Error: Ambiguous code block start marker. Found more than once in ./shared/common/src/types.ts, at lines 27,50
    at getSnippet (/home/jg/www/npm-library/node_modules/.pnpm/remark-code-snippets@1.1.0/node_modules/remark-code-snippets/dist/index.js:81:19)
    at transformer (/home/jg/www/npm-library/node_modules/.pnpm/remark-code-snippets@1.1.0/node_modules/remark-code-snippets/dist/index.js:62:30)
    at wrapped (file:///home/jg/www/npm-library/node_modules/.pnpm/trough@2.1.0/node_modules/trough/index.js:115:27)
    at next (file:///home/jg/www/npm-library/node_modules/.pnpm/trough@2.1.0/node_modules/trough/index.js:65:23)
    at done (file:///home/jg/www/npm-library/node_modules/.pnpm/trough@2.1.0/node_modules/trough/index.js:148:7)
    at then (file:///home/jg/www/npm-library/node_modules/.pnpm/trough@2.1.0/node_modules/trough/index.js:158:5)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Object.mdxLoader (/home/jg/www/npm-library/node_modules/.pnpm/@docusaurus+mdx-loader@3.1.0_@docusaurus+types@3.1.0_esbuild@0.19.11_react-dom@18.2.0_react@18.2.0/node_modules/@docusaurus/mdx-loader/lib/loader.js:130:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by unleashit** [comment]
False alarm, got it to work. Must have been caching issues either from the browser or webpack, or perhaps the regex in the plugin doesn't like numbers. In any case, after changing the hook names and a manual build it's all working as expected.
